[package]
authors = ["Brian Smith <brian@briansmith.org>"]
description = "Benchmarks of Rust crypto libraries."
name = "crypto_bench"
version = "0.1.0"

[lib]
name = "crypto_bench"
path = "crypto_bench.rs"
