[package]
authors = ["Brian Smith <brian@briansmith.org>"]
name = "crypto_bench_fastpbkdf2"
version = "0.1.0"

[lib]
name = "crypto_bench_fastpbkdf2"
path = "fastpbkdf2.rs"

[dependencies.crypto_bench]
path = "../crypto_bench"

[dependencies]
fastpbkdf2 = "0.1"
