[package]
authors = ["Brian Smith <brian@briansmith.org>"]
name = "crypto_bench_ring"
version = "0.1.0"
edition = "2018"

[lib]
name = "crypto_bench_ring"
path = "ring.rs"

[dependencies]
crypto_bench = { path = "../crypto_bench" }
ring = "0.16.11"
