[package]
name = "crypto_bench_sodiumoxide"
version = "0.1.0"

[lib]
name = "crypto_bench_sodiumoxide"
path = "sodiumoxide.rs"

[dependencies.crypto_bench]
path = "../crypto_bench"

[dependencies]
sodiumoxide = "0.2"
